home:
  uri: /home/
  controller: HomeController
  action: index
category:
  uri: /category/
  controller: CategoryController
  action: index
lang:
  url: /lang/
  controller: LanguageController
  action: setLanguage